# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0003_auto_20170821_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imaging_roi_created_by_related', to='misc.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='roidetection',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imaging_roidetection_created_by_related', to='misc.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='roidetection',
            name='f',
            field=models.ForeignKey(blank=True, help_text='array of size nT by nROIs giving raw fluorescence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roi_detection_f', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='roidetection',
            name='f0',
            field=models.ForeignKey(blank=True, help_text='array of size nT by nROIs giving resting fluorescence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roi_detection_f0', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='svdcompressedmovie',
            name='compressed_data_V',
            field=models.ForeignKey(blank=True, help_text='nSamples*nSVs binary array SVD-compression timecourses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='svd_movie_v', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='svdcompressedmovie',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imaging_svdcompressedmovie_created_by_related', to='misc.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='twophotonimaging',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imaging_twophotonimaging_created_by_related', to='misc.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='twophotonimaging',
            name='raw_data',
            field=models.ForeignKey(blank=True, help_text='array of size nT by nX by nY by nZ by nC', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_photon_raw', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='widefieldimaging',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imaging_widefieldimaging_created_by_related', to='misc.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='widefieldimaging',
            name='raw_data',
            field=models.ForeignKey(blank=True, help_text='pointer to nT by nX by nY by nC (colors) binary file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widefield_raw', to='data.Dataset'),
        ),
    ]
