# Generated by Django 2.0.6 on 2018-06-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0004_auto_20180111_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='roi_detection_id',
            field=models.ForeignKey(blank=True, help_text='link to detection entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='imaging.ROIDetection'),
        ),
        migrations.AlterField(
            model_name='roidetection',
            name='f',
            field=models.ForeignKey(blank=True, help_text='array of size nT by nROIs giving raw fluorescence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roi_detection_f', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='roidetection',
            name='f0',
            field=models.ForeignKey(blank=True, help_text='array of size nT by nROIs giving resting fluorescence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roi_detection_f0', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='roidetection',
            name='masks',
            field=models.ForeignKey(blank=True, help_text='array of size nROIs by nY by nX', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roi_detection_masks', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='roidetection',
            name='plane',
            field=models.ForeignKey(blank=True, help_text='array saying which plane each roi is found in. TODO: is this an ArrayField? JSON?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='roidetection',
            name='two_photon_imaging_id',
            field=models.ForeignKey(blank=True, help_text='2P imaging stack.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='imaging.TwoPhotonImaging'),
        ),
        migrations.AlterField(
            model_name='svdcompressedmovie',
            name='compressed_data_U',
            field=models.ForeignKey(blank=True, help_text='nSVs*nY*nX binary array giving normalized eigenframesSVD-compression eigenframes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='svd_movie_u', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='svdcompressedmovie',
            name='compressed_data_V',
            field=models.ForeignKey(blank=True, help_text='nSamples*nSVs binary array SVD-compression timecourses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='svd_movie_v', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='twophotonimaging',
            name='compressed_data',
            field=models.ForeignKey(blank=True, help_text='to Compressed_movie, if compression was run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two_photon_compressed', to='imaging.SVDCompressedMovie'),
        ),
        migrations.AlterField(
            model_name='twophotonimaging',
            name='image_position',
            field=models.ForeignKey(blank=True, help_text='Note if different planes have different alignment (e.g. flyback plane), this can’t be done in a single 3x3 transformation matrix, instead you would have an array of 3x2 matrices. TODO: how do we deal with this?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.CoordinateTransformation'),
        ),
        migrations.AlterField(
            model_name='twophotonimaging',
            name='raw_data',
            field=models.ForeignKey(blank=True, help_text='array of size nT by nX by nY by nZ by nC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two_photon_raw', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='twophotonimaging',
            name='reference_stack',
            field=models.ForeignKey(blank=True, help_text='TODO: reference stack / BrainImage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two_photon_reference', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='widefieldimaging',
            name='compressed_data',
            field=models.ForeignKey(blank=True, help_text='Link to SVD compressed movie, if compression was run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widefield_compressed', to='imaging.SVDCompressedMovie'),
        ),
        migrations.AlterField(
            model_name='widefieldimaging',
            name='excitation_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.LightSource'),
        ),
        migrations.AlterField(
            model_name='widefieldimaging',
            name='image_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.CoordinateTransformation'),
        ),
        migrations.AlterField(
            model_name='widefieldimaging',
            name='raw_data',
            field=models.ForeignKey(blank=True, help_text='pointer to nT by nX by nY by nC (colors) binary file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widefield_raw', to='data.Dataset'),
        ),
    ]
