# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roidetection',
            name='two_photon_imaging_id',
            field=models.ForeignKey(blank=True, help_text='2P imaging stack.', null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging.TwoPhotonImaging'),
        ),
        migrations.AlterField(
            model_name='widefieldimaging',
            name='excitation_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.LightSource'),
        ),
    ]
