# Generated by Django 2.0.6 on 2018-07-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('equipment', '0001_initial'),
        ('electrophysiology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probemodel',
            name='probe_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Supplier'),
        ),
        migrations.AddField(
            model_name='probemodel',
            name='site_positions',
            field=models.ForeignKey(blank=True, help_text='numerical array of size nSites x 2 giving locations of each contact site  in local coordinates. Probe tip is at the origin.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='probeinsertion',
            name='channel_mapping',
            field=models.ForeignKey(blank=True, help_text='numerical array of size nSites x 1 giving the row of the raw data file for each contact site. You will have one of these files per probe, including if you record multiple probes through the same amplifier. Sites that were not recorded should have NaN or -1.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probe_insertion_channel_mapping', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='probeinsertion',
            name='extracellular_recording',
            field=models.ForeignKey(help_text='id of extracellular recording', on_delete=django.db.models.deletion.CASCADE, to='electrophysiology.ExtracellularRecording'),
        ),
        migrations.AddField(
            model_name='probeinsertion',
            name='probe_model',
            field=models.ForeignKey(blank=True, help_text='model of probe used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electrophysiology.ProbeModel'),
        ),
    ]
