# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170821_0923'),
        ('electrophysiology', '0002_auto_20170808_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmapping',
            name='extracellular_recording',
        ),
        migrations.RemoveField(
            model_name='channelmapping',
            name='probe_insertion',
        ),
        migrations.RemoveField(
            model_name='intracellularrecording',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='spikesorting',
            name='cluster_data',
        ),
        migrations.RemoveField(
            model_name='spikesorting',
            name='spikes',
        ),
        migrations.AddField(
            model_name='probeinsertion',
            name='channel_mapping',
            field=models.ForeignKey(blank=True, help_text='numerical array of size nSites x 1 giving the row of the raw data file for each contact site. You will have one of these files per probe, including if you record multiple probes through the same amplifier. Sites that were not recorded should have NaN or -1.', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='probeinsertion',
            name='extracellular_recording',
            field=models.ForeignKey(default=None, help_text='id of extracellular recording', on_delete=django.db.models.deletion.CASCADE, to='electrophysiology.ExtracellularRecording'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spikesorting',
            name='probe_insertion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='spike_sorting_probe', to='electrophysiology.ExtracellularRecording'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extracellularrecording',
            name='gains',
            field=models.ForeignKey(blank=True, help_text='dataset containing gain of each channel  microvolts/bit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracellular_gains', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='spikesortedunit',
            name='cluster_group',
            field=models.CharField(choices=[('0', 'Noise'), ('1', 'Multi-unit activity'), ('2', 'Single-unit activity'), ('3', 'Unsorted')], help_text='Human decision on cluster group', max_length=1),
        ),
        migrations.DeleteModel(
            name='ChannelMapping',
        ),
    ]
