# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20171019_1017'),
        ('electrophysiology', '0003_auto_20170821_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracellularrecording',
            name='timeseries_ptr',
        ),
        migrations.RemoveField(
            model_name='spikesorting',
            name='eventseries_ptr',
        ),
        migrations.AddField(
            model_name='extracellularrecording',
            name='dataset_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Dataset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spikesorting',
            name='dataset_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Dataset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extracellularrecording',
            name='lfp',
            field=models.ForeignKey(blank=True, help_text='lfp: low-pass filtered and downsampled', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracellular_recording_lfp', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='probeinsertion',
            name='channel_mapping',
            field=models.ForeignKey(blank=True, help_text='numerical array of size nSites x 1 giving the row of the raw data file for each contact site. You will have one of these files per probe, including if you record multiple probes through the same amplifier. Sites that were not recorded should have NaN or -1.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='probe_insertion_channel_mapping', to='data.Dataset'),
        ),
    ]
