# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 12:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=1000)),
                ('is_folder', models.BooleanField()),
                ('tape_sequential_number', models.IntegerField(blank=True, null=True)),
                ('md5', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveDataLocation',
            fields=[
                ('datalocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.DataLocation')),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('tape_contents', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('physical_archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PhysicalArchive')),
            ],
            bases=('data.datalocation',),
        ),
        migrations.CreateModel(
            name='LocalDataLocation',
            fields=[
                ('datalocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.DataLocation')),
                ('hostname', models.CharField(blank=True, max_length=1000, null=True)),
                ('path', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            bases=('data.datalocation',),
        ),
        migrations.CreateModel(
            name='NetworkDataLocation',
            fields=[
                ('datalocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.DataLocation')),
                ('fqdn', models.CharField(blank=True, max_length=1000, null=True)),
                ('share', models.CharField(blank=True, max_length=1000, null=True)),
                ('path', models.CharField(blank=True, max_length=1000, null=True)),
                ('nfs_supported', models.BooleanField()),
                ('smb_supported', models.BooleanField()),
                ('afp_supported', models.BooleanField()),
            ],
            bases=('data.datalocation',),
        ),
        migrations.AddField(
            model_name='filerecord',
            name='data_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DataLocation'),
        ),
    ]
