# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarepository',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_data.datarepository_set+', to='contenttypes.ContentType'),
        ),
    ]
