# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_datarepository_polymorphic_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarepository',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
