# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20160506_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseFileCollection',
            new_name='FileCollection',
        ),
    ]
