# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0003_auto_20160507_1803'),
        ('data', '0005_auto_20160506_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogicalFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('md5', models.CharField(blank=True, max_length=255, null=True)),
                ('filename', models.CharField(max_length=1000)),
                ('is_folder', models.BooleanField()),
                ('fileset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Fileset')),
            ],
        ),
        migrations.RemoveField(
            model_name='filerecord',
            name='collection',
        ),
        migrations.DeleteModel(
            name='FileCollection',
        ),
        migrations.AddField(
            model_name='filerecord',
            name='file',
            field=models.ForeignKey(default='123e4567-e89b-12d3-a456-426655440000', on_delete=django.db.models.deletion.CASCADE, to='data.LogicalFile'),
            preserve_default=False,
        ),
    ]
