# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 15:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial', models.CharField(blank=True, help_text='The serial number of the appliance.', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('descriptive_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('R', 'Regular'), ('I', 'IVC')], default='R', help_text='Is this an IVC or regular cage?', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentManufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="i.e. 'NeuroNexus'", max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="e.g. 'BrainScanner 4X'", max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentManufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Amplifier',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipment.Appliance')),
            ],
            options={
                'abstract': False,
            },
            bases=('equipment.appliance',),
        ),
        migrations.CreateModel(
            name='ExtracellularProbe',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipment.Appliance')),
                ('prb', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The PRB file describing the probe connectivity and geometry, in JSON', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('equipment.appliance',),
        ),
        migrations.CreateModel(
            name='WeighingScale',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipment.Appliance')),
            ],
            options={
                'abstract': False,
            },
            bases=('equipment.appliance',),
        ),
        migrations.AddField(
            model_name='cage',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.ExperimentLocation'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='equipment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentModel'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location of the appliance.', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.ExperimentLocation'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_equipment.appliance_set+', to='contenttypes.ContentType'),
        ),
    ]
