# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAQ',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipment.Appliance')),
            ],
            options={
                'abstract': False,
            },
            bases=('equipment.appliance',),
        ),
        migrations.CreateModel(
            name='PipettePuller',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipment.Appliance')),
            ],
            options={
                'abstract': False,
            },
            bases=('equipment.appliance',),
        ),
    ]
