# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 17:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amplifier',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipment.Appliance')),
            ],
            bases=('equipment.appliance',),
        ),
        migrations.CreateModel(
            name='EquipmentManufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentManufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ExtracellularProbe',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipment.Appliance')),
                ('prb', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            bases=('equipment.appliance',),
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='manufacturer_model',
        ),
        migrations.AddField(
            model_name='appliance',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.Location'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='equipment_model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentModel'),
            preserve_default=False,
        ),
    ]
