# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20160422_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='ExperimentLocation',
        ),
    ]
