# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('equipment', '0003_auto_20160423_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_equipment.appliance_set+', to='contenttypes.ContentType'),
        ),
    ]
