# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 19:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_appliance_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location of the appliance.', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.ExperimentLocation'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='serial',
            field=models.CharField(blank=True, help_text='The serial number of the appliance.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cage',
            name='type',
            field=models.CharField(choices=[('R', 'Regular'), ('I', 'IVC')], default='R', help_text='Is this an IVC or regular cage?', max_length=1),
        ),
        migrations.AlterField(
            model_name='equipmentmanufacturer',
            name='name',
            field=models.CharField(help_text="i.e. 'NeuroNexus'", max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='model_name',
            field=models.CharField(help_text="e.g. 'BrainScanner 4X'", max_length=255),
        ),
        migrations.AlterField(
            model_name='extracellularprobe',
            name='prb',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The PRB file describing the probe connectivity and geometry, in JSON', null=True),
        ),
    ]
