# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20170808_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='intervalseries',
            name='experiment',
        ),
    ]
