# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electrophysiology', '0003_auto_20170529_1136'),
        ('data', '0002_auto_20170529_1136'),
        ('actions', '0005_auto_20170529_1136'),
        ('behavior', '0004_auto_20170529_1136'),
        ('imaging', '0002_auto_20170529_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timestamp',
        ),
        migrations.AddField(
            model_name='timescale',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_timescale_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timescale',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_timescale_session_related', to='actions.Session'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_intervalseries_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='interval_times',
            field=models.ForeignKey(blank=True, help_text='n*2 array of start and end times', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_intervalseries_interval_times_related', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='interval_types',
            field=models.ForeignKey(blank=True, help_text='n*1 array listing the type of each interval', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_intervalseries_interval_types_related', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing  intermediate results', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_intervalseries_provenance_related', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_intervalseries_session_related', to='actions.Session'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='timescale',
            field=models.ForeignKey(blank=True, help_text='which timescale this is on', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Timescale'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='type_descriptions',
            field=models.ForeignKey(blank=True, help_text='interval series type descriptions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_intervalseries_type_descriptions_related', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_eventseries_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='event_times',
            field=models.ForeignKey(blank=True, help_text='n*1 array of times', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_eventseries_event_times_related', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='event_types',
            field=models.ForeignKey(blank=True, help_text='n*1 array listing the type of each event, numbers or strings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_eventseries_event_types_related', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_eventseries_provenance_related', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_eventseries_session_related', to='actions.Session'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='timescale',
            field=models.ForeignKey(blank=True, help_text='which timescale this is on', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Timescale'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='type_descriptions',
            field=models.ForeignKey(blank=True, help_text='nTypes*2 text array (.tsv) describing event types', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_eventseries_type_descriptions_related', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='datarepository',
            name='repository_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DataRepositoryType'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='dataset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DatasetType'),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='timescale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Timescale'),
        ),
    ]
