# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170529_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarepositorytype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='datasettype',
            name='name',
            field=models.CharField(blank=True, help_text='description of data type', max_length=255, unique=True),
        ),
    ]
