# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_note'),
        ('data', '0005_auto_20180111_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataformat',
            old_name='alf_filename',
            new_name='filename_pattern',
        ),
        migrations.RenameField(
            model_name='datasettype',
            old_name='alf_filename',
            new_name='filename_pattern',
        ),
        migrations.AddField(
            model_name='datarepository',
            name='globus_is_personal',
            field=models.NullBooleanField(help_text='whether the Globus endpoint is personal or not. By default, Globus cannot transfer a file between two personal endpoints.'),
        ),
        migrations.AddField(
            model_name='datasettype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_datasettype_created_by_related', to='misc.OrderedUser'),
        ),
        migrations.AddField(
            model_name='datasettype',
            name='parent_dataset_type',
            field=models.ForeignKey(blank=True, help_text='hierachical parent of this DatasetType.', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DatasetType'),
        ),
        migrations.AlterField(
            model_name='dataformat',
            name='description',
            field=models.CharField(blank=True, help_text="Human-readable description of the file format e.g. 'npy-formatted square numerical array'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='dataformat',
            name='matlab_loader_function',
            field=models.CharField(blank=True, help_text="Name of MATLAB loader function'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='dataformat',
            name='python_loader_function',
            field=models.CharField(blank=True, help_text="Name of Python loader function'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='datarepository',
            name='globus_endpoint_id',
            field=models.UUIDField(blank=True, help_text='UUID of the globus endpoint', null=True),
        ),
        migrations.AlterField(
            model_name='datarepository',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='parent_dataset',
            field=models.ForeignKey(blank=True, help_text='hierachical parent of this Dataset.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_dataset', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_records', to='data.Dataset'),
        ),
    ]
