# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 18:38
from __future__ import unicode_literals
import os
import random
import string

import data.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20180510_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='parent_dataset',
        ),
        migrations.RemoveField(
            model_name='datasettype',
            name='parent_dataset_type',
        ),

        migrations.AlterField(
            model_name='dataformat',
            name='name',
            field=models.CharField(help_text="short identifying nickname, e..g 'npy'.", max_length=255, unique=True),
        ),

        # File extension
        migrations.AlterField(
            model_name='dataformat',
            name='filename_pattern',
            field=models.CharField(help_text='file extension, starting with a dot.', max_length=255, validators=[django.core.validators.RegexValidator('^\\.[^\\.]+$', code='invalid_file_extension', message='Invalid file extension, should start with a dot')]),
        ),
        migrations.RenameField(
            model_name='dataformat',
            old_name='filename_pattern',
            new_name='file_extension',
        ),

        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=255),
        ),

        migrations.AlterField(
            model_name='datasettype',
            name='filename_pattern',
            field=models.CharField(help_text="File name pattern (with wildcards) for this file in ALF naming convention. E.g. 'spikes.times.*' or '*.timestamps.*', or 'spikes.*.*' for a DataCollection, which would include all files starting with the word 'spikes'.", max_length=255, unique=True),
        ),

        migrations.AlterField(
            model_name='filerecord',
            name='relative_path',
            field=models.CharField(help_text='path name within repository', max_length=1000, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\_][^\\\\\\:]+$', code='invalid_path', message='Invalid path')]),
        ),

        migrations.AlterField(
            model_name='filerecord',
            name='data_repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DataRepository'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='data_format',
            field=models.ForeignKey(default=data.models.default_data_format, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.DataFormat'),
        ),
    ]
