# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 20:24
from __future__ import unicode_literals

import data.models
import django.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20180510_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset_type',
            field=models.ForeignKey(default=data.models.default_dataset_type, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.DatasetType'),
        ),
        migrations.AlterModelOptions(
            name='dataformat',
            options={'ordering': ('name',), 'verbose_name_plural': 'data formats'},
        ),
        migrations.AlterModelOptions(
            name='datarepository',
            options={'ordering': ('name',), 'verbose_name_plural': 'data repositories'},
        ),
        migrations.AlterModelOptions(
            name='datarepositorytype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='datasettype',
            options={'ordering': ('name',)},
        ),
    ]
