# Generated by Django 3.2.6 on 2022-06-24 15:14

import alyx.base
from django.db import migrations


def str2null(apps, _):
    DatasetType = apps.get_model('data', 'DatasetType')
    for dstype in DatasetType.objects.filter(filename_pattern=''):
        dstype.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_dataset_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasettype',
            name='filename_pattern',
            field=alyx.base.CharNullField(blank=True, help_text="File name pattern (with wildcards) for this file in ALF naming convention. E.g. 'spikes.times.*' or '*.timestamps.*', or 'spikes.*.*' for a DataCollection, which would include all files starting with the word 'spikes'.", max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(str2null),
    ]

