# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20180510_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarepository',
            name='url',
            field=models.URLField(blank=True, help_text='URL of the data repository, if it is accessible via HTTP', null=True),
        ),
    ]
