# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_datarepository_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarepository',
            old_name='url',
            new_name='data_url',
        ),
    ]
