# Generated by Django 5.2.8 on 2025-11-07 17:44

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_dataset_collection_alter_dataset_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarepository',
            name='timezone',
            field=models.CharField(blank=True, default=data.models.default_timezone, help_text='Timezone of the server (see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)', max_length=64),
        ),
    ]
