# Generated by Django 5.2.12 on 2026-06-22 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_alter_datarepository_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('description', models.TextField(blank=True)),
                ('importance', models.IntegerField(choices=[(50, 'Critical'), (40, 'Major'), (30, 'Minor'), (20, 'Insignificant')], default=20, help_text='50: CRITICAL / 40: MAJOR / 30: MINOR / 20: INSIGNIFICANT')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('version_affected', models.CharField(blank=True, max_length=64)),
                ('affected_date_start', models.DateField(blank=True, null=True)),
                ('affected_date_end', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_notices', to=settings.AUTH_USER_MODEL)),
                ('datasets', models.ManyToManyField(blank=True, related_name='data_notices', to='data.dataset')),
            ],
            options={
                'ordering': ('-importance', '-created_datetime', 'name'),
            },
        ),
    ]
