# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliance',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='notes',
            new_name='description',
        ),
    ]
