# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrophysiology', '0002_auto_20170808_1504'),
        ('behavior', '0002_auto_20170808_1504'),
        ('equipment', '0002_auto_20170704_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentmanufacturer',
            name='supplier_ptr',
        ),
        migrations.RemoveField(
            model_name='extracellularprobe',
            name='appliance_ptr',
        ),
        migrations.RemoveField(
            model_name='virussource',
            name='supplier_ptr',
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.Supplier'),
        ),
        migrations.AlterField(
            model_name='virusbatch',
            name='virus_source',
            field=models.ForeignKey(blank=True, help_text='Who supplied the virus', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.Supplier'),
        ),
        migrations.DeleteModel(
            name='EquipmentManufacturer',
        ),
        migrations.DeleteModel(
            name='ExtracellularProbe',
        ),
        migrations.DeleteModel(
            name='VirusSource',
        ),
    ]
