# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 14:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_note'),
        ('equipment', '0004_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.OrderedUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
