# Generated by Django 2.0.6 on 2018-06-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_labmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location of the appliance.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.LabLocation'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Supplier'),
        ),
        migrations.AlterField(
            model_name='virusbatch',
            name='virus_source',
            field=models.ForeignKey(blank=True, help_text='Who supplied the virus', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Supplier'),
        ),
    ]
