# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0002_auto_20160506_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupiltracking',
            name='movie_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pupil_tracking_movie', to='data.Fileset'),
        ),
        migrations.AlterField(
            model_name='pupiltracking',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pupil_tracking_provenance', to='data.Fileset'),
        ),
        migrations.AlterField(
            model_name='pupiltracking',
            name='x_y_d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pupil_tracking_x_y_d', to='data.Fileset'),
        ),
    ]
