# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0003_auto_20160509_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optogeneticstimulus',
            name='apparatus',
            field=models.ForeignKey(blank=True, help_text='e.g. Laser that was used for stimulation. TODO: should this be a ManyToManyField? Also what is this class? It should subclass Appliance rather than call it directly', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.Appliance'),
        ),
    ]
