# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20160507_1905'),
        ('behavior', '0003_auto_20160507_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupiltracking',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='pupiltracking',
            name='movie',
            field=models.ForeignKey(blank=True, help_text='Link to raw data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pupil_tracking_movie', to='data.Fileset'),
        ),
        migrations.AlterField(
            model_name='pupiltracking',
            name='description',
            field=models.TextField(blank=True, help_text='misc. narrative e.g. (“unit: mm” or “unknown scale factor”)', null=True),
        ),
        migrations.AlterField(
            model_name='pupiltracking',
            name='eye',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], default='L', help_text='Which eye was tracked; left or right', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pupiltracking',
            name='generating_software',
            field=models.CharField(blank=True, help_text='e.g. “PupilTracka 0.8.3”', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pupiltracking',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pupil_tracking_provenance', to='data.Fileset'),
        ),
        migrations.AlterField(
            model_name='pupiltracking',
            name='x_y_d',
            field=models.ForeignKey(blank=True, help_text='3xn timeseries giving x and y coordinates of center plus diameter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pupil_tracking_x_y_d', to='data.Fileset'),
        ),
    ]
