# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0004_auto_20160509_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optogeneticstimulus',
            name='apparatus',
            field=models.ForeignKey(blank=True, help_text='e.g. Laser that was used for stimulation.', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.Appliance'),
        ),
        migrations.AlterField(
            model_name='optogeneticstimulus',
            name='waveform',
            field=models.ForeignKey(blank=True, help_text='link to a file giving the waveform of each stimulus.?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optogenetic_stimulus_waveform', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='pupiltracking',
            name='eye',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], help_text='Which eye was tracked; left or right', max_length=1, null=True),
        ),
    ]
