# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 15:32
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('start_date_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=30)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirusBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('virus_type', models.CharField(blank=True, help_text='UPenn ID or equivalent', max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('virus_source', models.CharField(blank=True, help_text='Who sold the virus. TODO: make this a normalized table', max_length=255, null=True)),
                ('date_time_made', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('nominal_titer', models.FloatField(blank=True, help_text='TODO: What unit?', null=True)),
            ],
            options={
                'verbose_name_plural': 'virus batches',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actions.Action')),
            ],
            bases=('actions.action',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actions.Action')),
            ],
            bases=('actions.action',),
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actions.Action')),
                ('procedure', models.CharField(blank=True, help_text='The type of procedure(s) performed', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'surgeries',
            },
            bases=('actions.action',),
        ),
        migrations.CreateModel(
            name='VirusInjection',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actions.Action')),
                ('injection_volume', models.FloatField(blank=True, help_text='Volume in nanoliters', null=True)),
                ('rate_of_injection', models.FloatField(blank=True, help_text='TODO: Nanoliters per second / per minute?', null=True)),
                ('injection_type', models.CharField(blank=True, choices=[('I', 'Iontophoresis'), ('P', 'Pressure')], default='I', help_text='Whether the injection was through iontophoresis or pressure', max_length=1, null=True)),
            ],
            bases=('actions.action',),
        ),
        migrations.CreateModel(
            name='Weighing',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actions.Action')),
                ('weight', models.FloatField(help_text='Weight in grams')),
            ],
            bases=('actions.action',),
        ),
    ]
