# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20160422_1701'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='JSON',
            new_name='json',
        ),
        migrations.AddField(
            model_name='weighing',
            name='weighing_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.WeighingScale'),
        ),
        migrations.AlterField(
            model_name='action',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.Location'),
        ),
    ]
