# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0001_initial'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location at which the experiment was performed', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.ExperimentLocation'),
        ),
        migrations.AddField(
            model_name='action',
            name='subject',
            field=models.ForeignKey(help_text='The subject on which this action was performed', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='action',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The user(s) involved in this action', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weighing',
            name='weighing_scale',
            field=models.ForeignKey(blank=True, help_text='The scale record that was used to weigh the subject', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.WeighingScale'),
        ),
        migrations.AddField(
            model_name='virusinjection',
            name='virus_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.VirusBatch'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='brain_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.BrainLocation'),
        ),
    ]
