# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 13:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20160509_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location at which the action was performed', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.ExperimentLocation'),
        ),
        migrations.AlterField(
            model_name='action',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='Short text strings to allow searching', null=True, size=30),
        ),
        migrations.AlterField(
            model_name='virusinjection',
            name='virus_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.VirusBatch'),
        ),
        migrations.DeleteModel(
            name='VirusBatch',
        ),
    ]
