# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_experiment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Virus_Batch',
            new_name='VirusBatch',
        ),
        migrations.RenameModel(
            old_name='Virus_Injection',
            new_name='VirusInjection',
        ),
        migrations.AlterModelOptions(
            name='virusbatch',
            options={'verbose_name_plural': 'Virus batches'},
        ),
    ]
