# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_auto_20160506_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virusbatch',
            options={'verbose_name_plural': 'virus batches'},
        ),
    ]
