# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_remove_experiment_is_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location at which the experiment was performed', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.ExperimentLocation'),
        ),
        migrations.AlterField(
            model_name='action',
            name='subject',
            field=models.ForeignKey(help_text='The subject on which this action was performed', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='subjects.Subject'),
        ),
        migrations.AlterField(
            model_name='action',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The user(s) involved in this action', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='brain_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.BrainLocation'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='procedure',
            field=models.CharField(blank=True, help_text='The type of procedure(s) performed', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='virusbatch',
            name='nominal_titer',
            field=models.FloatField(blank=True, help_text='TODO: What unit?', null=True),
        ),
        migrations.AlterField(
            model_name='virusbatch',
            name='virus_source',
            field=models.CharField(blank=True, help_text='Who sold the virus. TODO: make this a normalized table', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='virusbatch',
            name='virus_type',
            field=models.CharField(blank=True, help_text='UPenn ID or equivalent', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='virusinjection',
            name='injection_type',
            field=models.CharField(blank=True, choices=[('I', 'Iontophoresis'), ('P', 'Pressure')], default='I', help_text='Whether the injection was through iontophoresis or pressure', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='virusinjection',
            name='injection_volume',
            field=models.FloatField(blank=True, help_text='Volume in nanoliters', null=True),
        ),
        migrations.AlterField(
            model_name='virusinjection',
            name='rate_of_injection',
            field=models.FloatField(blank=True, help_text='TODO: Nanoliters per second / per minute?', null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='weighing_scale',
            field=models.ForeignKey(blank=True, help_text='The scale record that was used to weigh the subject', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.WeighingScale'),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='weight',
            field=models.FloatField(help_text='Weight in grams'),
        ),
    ]
