# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 10:20
from __future__ import unicode_literals
import json
import os.path as op
import sys

from dateutil.parser import parse as parse_
from django.conf import settings
from django.contrib.auth.models import User
from django.core.management import call_command
from django.db import migrations
from django.utils.dateparse import parse_datetime
from django.utils.timezone import is_aware, make_aware

from actions.models import Surgery
from subjects.models import Species, Subject, Line, GenotypeTest, Sequence, Litter, Cage

from core import DATA_DIR, get_table, get_sheet_doc, sheet_to_table


# Functions
# ------------------------------------------------------------------------------------------------

def parse(date_str):
    if not date_str:
        return
    ret = parse_(date_str)
    if not is_aware(ret):
        ret = make_aware(ret)
    return ret


def get_user(initials):
    nickname = {
        'AL': 'armin',
        'AP': 'andy',
        'CR': 'charu',
        'NS': 'nick',
        'ICL': 'i-chun',
        'PZH': 'peter',
        'MDia': 'mika',
        'MK': 'michael',
        'SF': 'sam',
        'MP': 'marius',
        'PC': 'pip',
        'MW': 'miles',
        'LF': 'laura',
    }[initials]
    return User.objects.get(username=nickname)


def get_line(sheet_name, table_line=None):
    name = {row['Sheet Name']: row['NAME'] for row in table_line}[sheet_name]
    return Line.objects.get(name=name)


def get_subject(nickname):
    if not nickname:
        return
    return Subject.objects.get(nickname=nickname)


# Import 1
# ------------------------------------------------------------------------------------------------

def get_line_kwargs(row):
    return dict(
        name=row['NAME'],
        auto_name=row['NICKNAME'],
        target_phenotype=row['LONG NAME'],
        description=row['BLURB'],
        json=json.loads('''
            {"stock_no": "%s",
             "source": "%s",
             "genotype": "%s",
             "bru_strain_number": "%s",
             "atlas": "%s"}
        ''' % (row['STOCK NO'],
               row['SOURCE'],
               row['GENOTYPE'],
               row['BRU STRAIN NUMBER'],
               row['ATLAS'],
              ))
    )


def get_subjects_kwargs(row, mouse=None, table_line=None):
    sc = Subject.SEVERITY_CHOICES
    # Lookup severity.
    severity = {v: k for (k, v) in dict(sc).items()}.get(row['Actual Severity'], None)
    return dict(
         nickname=row['Nickname'],
         birth_date=parse(row['Date of Birth']) if row['Date of Birth'] else None,
         adverse_effects=row['Adverse Effects'],
         death_date=parse(row['Cull Date']) if row['Cull Date'] else None,
         cull_method=row['Cull Method'],
         actual_severity=severity,
         protocol_number=row['Protocol #'],
         responsible_user=get_user(row['Responsible User']),
         species=mouse,
         line=get_line(row['Line'], table_line=table_line),
     )


def get_surgery_kwargs(row):
    return dict(
        users=[get_user(initials.strip()) for initials in row['Surgery Performed By'].split(',')],
        subject=get_subject(row['Nickname']),
        start_time=parse(row['Date of surgery']),
        outcome_type=row['Acute/ Recovery'][0],
        narrative=row['Procedures'],
    )


# Import 2
# ------------------------------------------------------------------------------------------------

def get_line_doc():
    return get_sheet_doc('Mice Stock - C57 and Transgenic')


def import_line(doc, line_name):
    ws = doc.worksheet(line_name)
    cols = ws.row_values(3)
    genotype_cols = [c[8:].strip() for c in cols if c.startswith('Genotype')]
    # Get or create line's sequences.
    sequences = {name: Sequence.objects.get_or_create(informal_name=name)
                 for name in genotype_cols}
    # Create line.
    line = Line.objects.get_or_create(name=line_name)
    print(line)
    print(list(sequences.values()))
    line.sequences = list(sequences.values())
    print("Created line %s with %d sequences." % (line_name, len(sequences)))

    # Importing the subjects.
    table = sheet_to_table(ws)
    subjects = []
    for row in table:
        kwargs = {}
        kwargs['ear_mark'] = row['Ear mark']
        kwargs['sex'] = row['Sex']
        kwargs['notes'] = row['Notes']
        kwargs['birth_date'] = parse(row['DOB'])
        kwargs['death_date'] = parse(row['death date'])
        kwargs['wean_date'] = parse(row.get('wean date', None))
        kwargs['nickname'] = row['autoname']
        kwargs['json'] = {k: row[k] for k in ('LAMIS Cage number', 'F Parent', 'M Parent')}

        # Create the subject.
        subject = Subject.objects.get_or_create(**kwargs)

        # Set the genotype.
        for c in cols:
            if not c.startswith('Genotype'):
                continue
            test_result = row[c]
            if not rest_result:
                continue
            # Get the sequence.
            sequence = sequences[c[8:].strip()]
            # Set the genotype test.
            gt = GenotypeTest.objects.get_or_create(subject=subject,
                                                    sequence=sequence,
                                                    test_result=test_result)
        subject.save()
        subjects.append(subject)
    print("Added %d subjects." % len(subjects))

    # Set the litters.
    for subject in subjects:
        litter = Litter.objects.get_or_create(birth_date=subject.birth_date,
                                              mother=subject.json['F Parent'],
                                              father=subject.json['M Parent'])
        subject.litter = litter
        subject.save()

    # Set autoname inedx.
    line.subject_autoname_index = max(row['n'] for row in table)

    line.save()


# Migrations
# ------------------------------------------------------------------------------------------------

def load_static(apps, schema_editor):
    path = op.join(DATA_DIR, 'dumped_static.json')
    call_command('loaddata', path)


def make_admin(apps, schema_editor):
    for username in ('Experiment', 'charu', 'cyrille', 'nick'):
        u = User.objects.get(username=username)
        u.is_superuser = True
        u.save()


def load_worksheets_1(apps, schema_editor):
    mouse = Species.objects.get(display_name='Laboratory mouse')
    table_subjects = get_table('Mice Procedure Log', 'PROCEDURE LOG')
    table_line = get_table('Mice Stock - C57 and Transgenic', 'Current lines in the unit')

    # Add lines.
    Line.objects.bulk_create(Line(**get_line_kwargs(row)) for row in table_line)
    print("%d lines added." % len(table_line))

    # Add subjects.
    Subject.objects.bulk_create(Subject(**get_subjects_kwargs(row,
                                                              mouse=mouse,
                                                              table_line=table_line,
                                                              ))
                                for row in table_subjects
                                if row['Nickname'])
    print("%d subjects added." % len(table_subjects))

    # Add surgeries.
    Surgery.objects.bulk_create(Surgery(**get_surgery_kwargs(row))
                                for row in table_subjects
                                if row['Nickname'])
    print("%d surgeries added." % len(table_subjects))


def load_worksheets_2(apps, schema_editor):
    mouse = Species.objects.get(display_name='Laboratory mouse')
    doc = get_line_doc()
    sheets = doc.worksheets()
    # TODO: loop over lines
    line_name = 'Camk2a-tTa'
    import_line(doc, line_name)


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '__latest__'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(load_static),
        migrations.RunPython(make_admin),
        migrations.RunPython(load_worksheets_2),
    ]
