# Generated by Django 2.1.2 on 2018-10-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zygosityrule',
            unique_together={('line', 'allele', 'sequence0', 'sequence0_result', 'sequence1', 'sequence1_result')},
        ),
    ]
