# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breedingpair',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='litter',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='subjectrequest',
            old_name='notes',
            new_name='description',
        ),
    ]
