# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 17:23
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.AlterField(
            model_name='subject',
            name='responsible_user',
            field=models.ForeignKey(blank=True, default=5, help_text='Who has primary or legal responsibility for the subject.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_responsible', to='actions.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='subjectrequest',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Who requested this subject.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_requested', to='actions.OrderedUser'),
        ),
    ]
