# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 10:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_note'),
        ('data', '0006_auto_20180319_1010'),
        ('subjects', '0002_auto_20170704_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('name', models.CharField(blank=True, help_text='Project name', max_length=255, unique=True)),
                ('description', models.CharField(blank=True, help_text='Description of the project', max_length=1023)),
                ('repositories', models.ManyToManyField(blank=True, help_text='Related DataRepository instances. Any file which is registered to Alyx is automatically copied to all repositories assigned to its project.', to='data.DataRepository')),
                ('users', models.ManyToManyField(blank=True, help_text='Persons associated to the project.', to='misc.OrderedUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Project associated to this session', to='subjects.Project'),
        ),
    ]
