# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import subjects.models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20170506_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='protocol_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='source',
            field=models.ForeignKey(blank=True, default=subjects.models._default_source, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.Source'),
        ),
    ]
