# Generated by Django 2.1.3 on 2018-12-10 12:45

from django.db import migrations, models
import django.db.models.deletion


def set_line_defaults(apps, schema_editor):
    Lab = apps.get_model('misc', 'Lab')
    lab = Lab.objects.first()
    Line = apps.get_model('subjects', 'line')
    Line.objects.update(lab=lab)


def set_subject_defaults(apps, schema_editor):
    Lab = apps.get_model('misc', 'Lab')
    lab = Lab.objects.first()
    Subject = apps.get_model('subjects', 'subject')
    Subject.objects.update(lab=lab)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_auto_20181119_0930'),
        ('subjects', '0002_auto_20181015_1026'),
    ]

    operations = [

        # Add non-nullable Line.lab (need to set a default lab).
        migrations.AddField(
            model_name='line',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.Lab'),
            preserve_default=False,
        ),
        migrations.RunPython(set_line_defaults, reverse_func),
        migrations.AlterField(
            model_name='line',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.Lab'),
            preserve_default=False,
        ),

        # Change nullable subject.lab to non-nullable (need to set a default lab).
        migrations.RunPython(set_subject_defaults, reverse_func),
        migrations.AlterField(
            model_name='subject',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.Lab'),
        ),

        migrations.AlterUniqueTogether(
            name='line',
            unique_together={('nickname', 'lab')},
        ),
    ]
