# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrequest',
            name='date_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
