# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20170704_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='lamis_strain_number',
            field=models.IntegerField(blank=True, help_text='LAMIS strain number', null=True),
        ),
    ]
