# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='reduced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='to_be_culled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='to_be_genotyped',
            field=models.BooleanField(default=False),
        ),
    ]
