# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-01 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20160621_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zygosity',
            options={'verbose_name_plural': 'zygosities'},
        ),
        migrations.AddField(
            model_name='cage',
            name='cage_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1, null=True),
        ),
    ]
