# Generated by Django 2.1.3 on 2018-12-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20181210_1245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='litter',
            unique_together={('name',)},
        ),
    ]
