# Generated by Django 2.1 on 2019-04-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20190124_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='repositories',
        ),
    ]
