# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20170302_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='auto_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='nickname',
            field=models.CharField(default='-', help_text="Easy-to-remember, unique name (e.g. 'Hercules').", max_length=255, unique=True),
        ),
    ]
