# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20170513_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='responsible_user',
            field=models.ForeignKey(blank=True, default=5, help_text='Who has primary or legal responsibility for the subject.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_responsible', to='misc.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='subjectrequest',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Who requested this subject.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_requested', to='misc.OrderedUser'),
        ),
    ]
