# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20170303_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linegenotypetest',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='linegenotypetest',
            name='subject',
        ),
        migrations.AlterField(
            model_name='line',
            name='sequences',
            field=models.ManyToManyField(to='subjects.Sequence'),
        ),
        migrations.DeleteModel(
            name='LineGenotypeTest',
        ),
    ]
