# Generated by Django 3.0 on 2019-12-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_remove_project_repositories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adverse effect',
        ),
        migrations.DeleteModel(
            name='Cull subject',
        ),
        migrations.CreateModel(
            name='Adverse_effect',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subjects.subject',),
        ),
        migrations.CreateModel(
            name='Cull_subject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subjects.subject',),
        ),
    ]
