# Generated by Django 2.1.3 on 2019-01-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20181214_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.Lab'),
        ),
    ]
