# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20170529_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='reduced_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
