# Generated by Django 2.0.6 on 2018-06-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedingpair',
            name='father',
            field=models.ForeignKey(blank=True, limit_choices_to={'sex': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litter_father', to='subjects.Subject'),
        ),
        migrations.AlterField(
            model_name='breedingpair',
            name='mother1',
            field=models.ForeignKey(blank=True, limit_choices_to={'sex': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother1', to='subjects.Subject'),
        ),
        migrations.AlterField(
            model_name='breedingpair',
            name='mother2',
            field=models.ForeignKey(blank=True, limit_choices_to={'sex': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother2', to='subjects.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Lab'),
        ),
    ]
