# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_subject_reduced_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
