# Generated by Django 3.0.6 on 2020-11-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_auto_20201015_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='implant_weight',
            field=models.FloatField(blank=True, help_text='Implant weight in grams', null=True),
        ),
    ]
