# Generated by Django 4.2.10 on 2024-03-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_alter_subject_nickname'),
        ('actions', '0024_surgery_implant_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='implant_weight',
        ),
    ]
