# Generated by Django 5.1.2 on 2025-02-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0013_remove_subject_implant_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adverse_effect',
        ),
        migrations.DeleteModel(
            name='Cull_subject',
        ),
        migrations.CreateModel(
            name='AdverseEffect',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subjects.subject',),
        ),
        migrations.CreateModel(
            name='CullSubject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subjects.subject',),
        ),
    ]
