# Generated by Django 5.2.8 on 2025-11-07 17:13
import logging

from django.db import migrations
from django.db.models import F


logger = logging.getLogger(__name__)


def update_reduced_date(apps, schema_editor):
    """Set reduced_date to death_date for all subjects where reduced is True but reduced_date is null."""
    Subject = apps.get_model('subjects', 'Subject')
    # Find all subjects where reduced is True but reduced_date is null
    subjects_true = Subject.objects.filter(reduced=True, reduced_date__isnull=True)
    # Update reduced_date to be the same as death date
    subjects_true.update(reduced_date=F('death_date'))
    logger.info(f'reduced_date set to death_date for {subjects_true.count():,g} subjects')


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_delete_adverse_effect_delete_cull_subject_and_more'),
    ]

    operations = [
        migrations.RunPython(update_reduced_date),
        migrations.RemoveField(
            model_name='subject',
            name='reduced',
        ),
    ]
