# Generated by Django 5.2.8 on 2025-11-07 21:30
import logging
from django.db import migrations

logger = logging.getLogger(__name__)


def update_culls(apps, schema_editor):
    """Set reduced_date to death_date for all subjects where reduced is True but reduced_date is null."""
    Subject = apps.get_model('subjects', 'Subject')
    Cull = apps.get_model('actions', 'Cull')
    CullMethod = apps.get_model('actions', 'CullMethod')

    # Find all subjects that have a cull_method but no cull
    subjects = Subject.objects.filter(cull__isnull=True).exclude(cull_method__isnull=True).exclude(cull_method='')
    updated = 0
    for subject in subjects:
        # deal with the synchronisation of cull object
        # Get the cull_method instance with the same name, if it exists, or None.
        cull_method = CullMethod.objects.filter(name=subject.cull_method).first()
        if subject.death_date:
            Cull.objects.create(
                subject=subject, cull_method=cull_method, date=subject.death_date,
                user=subject.responsible_user)
            updated += 1
    logger.info(f'Created cull for {updated:,g} subjects')


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0015_remove_subject_reduced'),
    ]

    operations = [
        migrations.RunPython(update_culls),
        migrations.RemoveField(
            model_name='subject',
            name='cull_method',
        ),
    ]
