SELECT subjects_subject.nickname AS subject_name,
subjects_sequence.name AS sequence_name,
subjects_genotypetest.test_result,
subjects_genotypetest.json,
subjects_genotypetest.id
FROM subjects_genotypetest
LEFT JOIN subjects_subject on subjects_subject.id=subjects_genotypetest.subject_id
LEFT JOIN subjects_sequence on subjects_sequence.id=subjects_genotypetest.sequence_id
