# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighing',
            name='subject',
            field=models.ForeignKey(help_text='The subject which was weighed', on_delete=django.db.models.deletion.CASCADE, related_name='weighings', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='weighing',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who weighed the subject', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weighing',
            name='weighing_scale',
            field=models.ForeignKey(blank=True, help_text='The scale record that was used to weigh the subject', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.WeighingScale'),
        ),
        migrations.AddField(
            model_name='waterrestriction',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location at which the action was performed', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.LabLocation'),
        ),
        migrations.AddField(
            model_name='waterrestriction',
            name='procedures',
            field=models.ManyToManyField(blank=True, help_text='The procedure(s) performed', to='actions.ProcedureType'),
        ),
        migrations.AddField(
            model_name='waterrestriction',
            name='subject',
            field=models.ForeignKey(help_text='The subject on which this action was performed', on_delete=django.db.models.deletion.CASCADE, related_name='actions_waterrestrictions', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='waterrestriction',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The user(s) involved in this action', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wateradministration',
            name='subject',
            field=models.ForeignKey(help_text='The subject to which water was administered', on_delete=django.db.models.deletion.CASCADE, related_name='water_administrations', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='wateradministration',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who administered water', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='virusinjection',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location at which the action was performed', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.LabLocation'),
        ),
        migrations.AddField(
            model_name='virusinjection',
            name='procedures',
            field=models.ManyToManyField(blank=True, help_text='The procedure(s) performed', to='actions.ProcedureType'),
        ),
        migrations.AddField(
            model_name='virusinjection',
            name='subject',
            field=models.ForeignKey(help_text='The subject on which this action was performed', on_delete=django.db.models.deletion.CASCADE, related_name='actions_virusinjections', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='virusinjection',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The user(s) involved in this action', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='virusinjection',
            name='virus_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.VirusBatch'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='brain_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.BrainLocation'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location at which the action was performed', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.LabLocation'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='procedures',
            field=models.ManyToManyField(blank=True, help_text='The procedure(s) performed', to='actions.ProcedureType'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='subject',
            field=models.ForeignKey(help_text='The subject on which this action was performed', on_delete=django.db.models.deletion.CASCADE, related_name='actions_surgerys', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The user(s) involved in this action', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otheraction',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location at which the action was performed', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.LabLocation'),
        ),
        migrations.AddField(
            model_name='otheraction',
            name='procedures',
            field=models.ManyToManyField(blank=True, help_text='The procedure(s) performed', to='actions.ProcedureType'),
        ),
        migrations.AddField(
            model_name='otheraction',
            name='subject',
            field=models.ForeignKey(help_text='The subject on which this action was performed', on_delete=django.db.models.deletion.CASCADE, related_name='actions_otheractions', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='otheraction',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The user(s) involved in this action', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experiment',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location at which the action was performed', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.LabLocation'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='procedures',
            field=models.ManyToManyField(blank=True, help_text='The procedure(s) performed', to='actions.ProcedureType'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='subject',
            field=models.ForeignKey(help_text='The subject on which this action was performed', on_delete=django.db.models.deletion.CASCADE, related_name='actions_experiments', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The user(s) involved in this action', to=settings.AUTH_USER_MODEL),
        ),
    ]
