# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 17:23
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('actions', '0002_auto_20170426_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'ordering': ['username'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='otheraction',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The user(s) involved in this action', to='actions.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='session',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The user(s) involved in this action', to='actions.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The user(s) involved in this action', to='actions.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='virusinjection',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The user(s) involved in this action', to='actions.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='wateradministration',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who administered water', null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='waterrestriction',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The user(s) involved in this action', to='actions.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who weighed the subject', null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.OrderedUser'),
        ),
    ]
