# Generated by Django 2.1 on 2018-11-22 19:23

import actions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20181119_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterrestriction',
            name='water_type',
            field=models.ForeignKey(blank=True, default=actions.models._default_water_type, help_text='Default Water Type when creating water admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='actions.WaterType'),
        ),
        migrations.AlterField(
            model_name='wateradministration',
            name='water_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actions.WaterType'),
        ),
    ]
