# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_auto_20180111_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='repositories',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.RemoveField(
            model_name='session',
            name='projects',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
