# Generated by Django 2.1.4 on 2019-07-16 11:58

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


def sync_cull(apps, scheme):
    print(apps)
    from subjects.models import Subject
    from actions.models import Cull

    subs = Subject.objects.filter(death_date__isnull=False)
    for sub in subs:
        cul = Cull.objects.create(subject=sub, date=sub.death_date, cull_method=sub.cull_method,
                                  user=sub.responsible_user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0004_remove_project_repositories'),
        ('actions', '0005_auto_20190124_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cull',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('date', models.DateField()),
                ('cull_method', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CullReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cull',
            name='cull_reason',
            field=models.ForeignKey(blank=True, help_text='Reason for culling the subject', null=True, on_delete=django.db.models.deletion.SET_NULL, to='actions.CullReason'),
        ),
        migrations.AddField(
            model_name='cull',
            name='subject',
            field=models.OneToOneField(help_text='The culled subject', on_delete=django.db.models.deletion.CASCADE, related_name='cull', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='cull',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who culled the subject', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(sync_cull),
    ]
