# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_lab'),
        ('actions', '0007_auto_20180510_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Project'),
        ),
    ]
