# Generated by Django 2.2.6 on 2020-01-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_session_qc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='qc',
        ),
        migrations.AddField(
            model_name='session',
            name='qc',
            field=models.IntegerField(choices=[(50, 'CRITICAL'), (40, 'ERROR'), (30, 'WARNING'), (20, 'NOT_SET'), (10, 'PASS')], default=20),
        ),
    ]
