# Generated by Django 2.0.6 on 2018-06-28 08:22

import actions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_session_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otheraction',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Lab'),
        ),
        migrations.AlterField(
            model_name='otheraction',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location at which the action was performed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.LabLocation'),
        ),
        migrations.AlterField(
            model_name='session',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Lab'),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location at which the action was performed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.LabLocation'),
        ),
        migrations.AlterField(
            model_name='session',
            name='parent_session',
            field=models.ForeignKey(blank=True, help_text='Hierarchical parent to this session', null=True, on_delete=django.db.models.deletion.SET_NULL, to='actions.Session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.Project'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='brain_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.BrainLocation'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Lab'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='location',
            field=models.ForeignKey(blank=True, default=actions.models._default_surgery_location, help_text='The physical location at which the surgery was performed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.LabLocation'),
        ),
        migrations.AlterField(
            model_name='virusinjection',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Lab'),
        ),
        migrations.AlterField(
            model_name='virusinjection',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location at which the action was performed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.LabLocation'),
        ),
        migrations.AlterField(
            model_name='virusinjection',
            name='virus_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.VirusBatch'),
        ),
        migrations.AlterField(
            model_name='wateradministration',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who administered water', null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='waterrestriction',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Lab'),
        ),
        migrations.AlterField(
            model_name='waterrestriction',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The physical location at which the action was performed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.LabLocation'),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who weighed the subject', null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.OrderedUser'),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='weighing_scale',
            field=models.ForeignKey(blank=True, help_text='The scale record that was used to weigh the subject', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.WeighingScale'),
        ),
    ]
