# Generated by Django 2.2.6 on 2020-02-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_alter_session_qc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EphysSession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('actions.session',),
        ),
    ]
