# Generated by Django 3.0.7 on 2021-02-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0013_auto_20201119_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='auto_datetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
    ]
