# Generated by Django 3.2.4 on 2021-06-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_session_auto_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cull',
            name='json',
            field=models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='cullmethod',
            name='json',
            field=models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='cullreason',
            name='json',
            field=models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='json',
            field=models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='json',
            field=models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='otheraction',
            name='json',
            field=models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='proceduretype',
            name='json',
            field=models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='extended_qc',
            field=models.JSONField(blank=True, help_text='Structured data about session QC,formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='json',
            field=models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='json',
            field=models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='virusinjection',
            name='json',
            field=models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='wateradministration',
            name='json',
            field=models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='waterrestriction',
            name='json',
            field=models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='watertype',
            name='json',
            field=models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='json',
            field=models.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True),
        ),
    ]
