# Generated by Django 4.1.7 on 2023-07-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0018_session_projects_alter_session_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingSession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('actions.session',),
        ),
    ]
