# Generated by Django 4.1.5 on 2023-02-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0012_taskprotocol'),
        ('actions', '0018_session_projects_alter_session_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='task_protocols',
            field=models.ManyToManyField(blank=True, to='experiments.taskprotocol', verbose_name='Session task protocols'),
        ),
        migrations.AlterField(
            model_name='session',
            name='task_protocol',
            field=models.CharField(blank=True, default='old task protocol', max_length=1023),
        ),
    ]
