# Generated by Django 4.1.7 on 2023-07-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0019_imagingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('responsible_user_change', 'responsible user has changed'), ('mouse_underweight', 'mouse is underweight'), ('mouse_water', 'water to give to mouse'), ('mouse_training', 'check training days'), ('mouse_not_weighed', 'no weight entered for date')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='notification_type',
            field=models.CharField(choices=[('responsible_user_change', 'responsible user has changed'), ('mouse_underweight', 'mouse is underweight'), ('mouse_water', 'water to give to mouse'), ('mouse_training', 'check training days'), ('mouse_not_weighed', 'no weight entered for date')], max_length=32),
        ),
    ]
