# Generated by Django 4.2.10 on 2024-03-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0020_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='extended_qc',
            field=models.JSONField(blank=True, help_text='Structured data about session QC, formatted in a user-defined way', null=True),
        ),
    ]
