# Generated by Django 4.2.10 on 2024-03-14 14:28
import logging

from django.db import migrations
from django.db.models import F, Q

logger = logging.getLogger(__name__)


def project2projects(apps, schema_editor):
    """
    Find sessions where the project field (singular) value is not in the projects (plural) many-to-many
    field and updates them.

    Tested on local instance.
    """
    # Data migrations run against whichever database `migrate --database` names, so
    # every query has to be told: the default manager would use `default` instead.
    db = schema_editor.connection.alias
    Session = apps.get_model('actions', 'Session')
    sessions = Session.objects.using(db).exclude(Q(project__isnull=True) | Q(projects=F('project')))
    # Counted up front: once the loop below has run, this queryset matches nothing, so
    # reporting its count afterwards would always say zero.
    n_sessions = sessions.count()

    # Check query worked
    # from iblutil.util import ensure_list
    # for session in sessions.values('pk', 'project', 'projects'):
    #     assert session['project'] not in ensure_list(session['projects'])

    for session in sessions:
        session.projects.add(session.project)
        # session.project = None
        # session.save()  # No need to save

    assert Session.objects.using(db).exclude(
        Q(project__isnull=True) | Q(projects=F('project'))).count() == 0
    logger.info(f'project -> projects: {n_sessions:,g} sessions updated')


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0021_alter_session_extended_qc'),
    ]

    operations = [migrations.RunPython(project2projects)]
