# Generated by Django 4.2.10 on 2024-03-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0022_project_to_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='project',
        ),
    ]
