# Generated by Django 4.2.10 on 2024-03-15 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0023_remove_session_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='implant_weight',
            field=models.FloatField(blank=True, default=0, help_text='Implant weight in grams', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='surgery',
            constraint=models.CheckConstraint(condition=models.Q(('implant_weight__gte', 0)), name='implant_weight_gte_0'),
        ),
    ]
