# Generated by Django 5.1.2 on 2024-11-19 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0025_move_implant_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='implant_weight',
            field=models.FloatField(help_text='Implant weight in grams', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
