services:
  django:
    image: public.ecr.aws/p4h6o9n8/alyx
    container_name: alyx
    ports:
      - "8080:8080"
      - "443:443"
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
      - "80:80"
    env_file: .env
    command: >
      bash -c "python /var/www/alyx/alyx/manage.py collectstatic --noinput &&
               /usr/sbin/apache2ctl -DFOREGROUND"
    restart: always
    volumes:
      - /var/log/apache2:/var/log/apache2
      - /var/log/alyx:/var/log/alyx
      - /etc/letsencrypt:/etc/apache2/ssl
