# Generated by Django 2.0.6 on 2018-07-09 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('behavior', '0001_initial'),
        ('equipment', '0001_initial'),
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0002_auto_20180709_1644'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupiltracking',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_pupiltracking_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pupiltracking',
            name='movie',
            field=models.ForeignKey(blank=True, help_text='Link to raw data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pupil_tracking_movie', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='pupiltracking',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pupil_tracking_provenance', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='pupiltracking',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_pupiltracking_session_related', to='actions.Session'),
        ),
        migrations.AddField(
            model_name='pupiltracking',
            name='x_y_d',
            field=models.ForeignKey(blank=True, help_text='n*3 timeseries giving x and y coordinates of center plus diameter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pupil_tracking_x_y_d', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='pharmacology',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_pharmacology_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacology',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_pharmacology_provenance_related', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='pharmacology',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_pharmacology_session_related', to='actions.Session'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='apparatus',
            field=models.ForeignKey(blank=True, help_text='e.g. Laser that was used for stimulation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Appliance'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='brain_location',
            field=models.ForeignKey(blank=True, help_text='of fiber tip, craniotomy, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.BrainLocation'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_optogeneticstimulus_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='power',
            field=models.ForeignKey(blank=True, help_text='link to an n*1 array giving each pulse power', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optogenetic_stimulus_power', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_optogeneticstimulus_provenance_related', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_optogeneticstimulus_session_related', to='actions.Session'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='stimulus_positions',
            field=models.ForeignKey(blank=True, help_text='link to an n*3 array of stimulus positions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optogenetic_stimulus_positions', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='stimulus_times',
            field=models.ForeignKey(blank=True, help_text='link to an n*2 array of start and stop of each pulse (sec)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optogenetic_stimulus_times', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='waveform',
            field=models.ForeignKey(blank=True, help_text='link to a file giving the waveform of each stimulus.?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optogenetic_stimulus_waveform', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_intervalseries_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='interval_times',
            field=models.ForeignKey(blank=True, help_text='n*2 array, with associated array of row labels.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interval_series_interval_times', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='interval_types',
            field=models.ForeignKey(blank=True, help_text='n*1 array listing the type of each interval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interval_series_interval_descriptions', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interval_series_provenance', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_intervalseries_session_related', to='actions.Session'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='type_descriptions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='headtracking',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_headtracking_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='headtracking',
            name='movie',
            field=models.ForeignKey(blank=True, help_text='Link to raw data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_tracking_movie', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='headtracking',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_tracking_provenance', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='headtracking',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_headtracking_session_related', to='actions.Session'),
        ),
        migrations.AddField(
            model_name='headtracking',
            name='x_y_theta',
            field=models.ForeignKey(blank=True, help_text='3*n timeseries giving x and y coordinates of head plus angle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_tracking_x_y_d', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_eventseries_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='event_times',
            field=models.ForeignKey(blank=True, help_text='n*1 array of times in seconds (universal timescale)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_series_event_times', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='event_types_id',
            field=models.ForeignKey(blank=True, help_text='n*1 array listing the type of each event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_series_event_descriptions', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_series_provenance', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_eventseries_session_related', to='actions.Session'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='type_descriptions_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Dataset'),
        ),
    ]
