# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_experiment'),
        ('data', '0002_auto_20170808_1504'),
        ('behavior', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventseries',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='headtracking',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='intervalseries',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='optogeneticstimulus',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='pharmacology',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='pupiltracking',
            name='created_date',
        ),
        migrations.AddField(
            model_name='eventseries',
            name='created_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The creation datetime.', null=True),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='experiment',
            field=models.ForeignKey(blank=True, help_text='The Experiment to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_eventseries_session_related', to='actions.Experiment'),
        ),
        migrations.AddField(
            model_name='headtracking',
            name='created_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The creation datetime.', null=True),
        ),
        migrations.AddField(
            model_name='headtracking',
            name='experiment',
            field=models.ForeignKey(blank=True, help_text='The Experiment to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_headtracking_session_related', to='actions.Experiment'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='created_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The creation datetime.', null=True),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='experiment',
            field=models.ForeignKey(blank=True, help_text='The Experiment to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_intervalseries_session_related', to='actions.Experiment'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='created_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The creation datetime.', null=True),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='experiment',
            field=models.ForeignKey(blank=True, help_text='The Experiment to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_optogeneticstimulus_session_related', to='actions.Experiment'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='generating_software',
            field=models.CharField(blank=True, help_text="e.g. 'ChoiceWorld 0.8.3'", max_length=255),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_optogeneticstimulus_provenance_related', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='pharmacology',
            name='created_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The creation datetime.', null=True),
        ),
        migrations.AddField(
            model_name='pharmacology',
            name='experiment',
            field=models.ForeignKey(blank=True, help_text='The Experiment to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_pharmacology_session_related', to='actions.Experiment'),
        ),
        migrations.AddField(
            model_name='pharmacology',
            name='generating_software',
            field=models.CharField(blank=True, help_text="e.g. 'ChoiceWorld 0.8.3'", max_length=255),
        ),
        migrations.AddField(
            model_name='pharmacology',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_pharmacology_provenance_related', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='pupiltracking',
            name='created_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The creation datetime.', null=True),
        ),
        migrations.AddField(
            model_name='pupiltracking',
            name='experiment',
            field=models.ForeignKey(blank=True, help_text='The Experiment to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_pupiltracking_session_related', to='actions.Experiment'),
        ),
    ]
