# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('data', '0001_initial'),
        ('behavior', '0002_auto_20170301_1600'),
        ('actions', '0002_auto_20170301_1600'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='apparatus',
            field=models.ForeignKey(blank=True, help_text='e.g. Laser that was used for stimulation.', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.Appliance'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='brain_location',
            field=models.ForeignKey(blank=True, help_text='of fiber tip, craniotomy, etc.', null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.BrainLocation'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='experiment',
            field=models.ForeignKey(help_text='The Experiment to which this data belongs', on_delete=django.db.models.deletion.CASCADE, related_name='behavior_optogeneticstimulus_related', to='actions.Experiment'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='power',
            field=models.ForeignKey(blank=True, help_text='link to an n*1 array giving each pulse power', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optogenetic_stimulus_power', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='stimulus_positions',
            field=models.ForeignKey(blank=True, help_text='link to an n*3 array of stimulus positions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optogenetic_stimulus_positions', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='stimulus_times',
            field=models.ForeignKey(blank=True, help_text='link to an n*2 array of start and stop of each pulse (sec)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optogenetic_stimulus_times', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='waveform',
            field=models.ForeignKey(blank=True, help_text='link to a file giving the waveform of each stimulus.?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optogenetic_stimulus_waveform', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='experiment',
            field=models.ForeignKey(help_text='The Experiment to which this data belongs', on_delete=django.db.models.deletion.CASCADE, related_name='behavior_intervalseries_related', to='actions.Experiment'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='interval_descriptions',
            field=models.ForeignKey(blank=True, help_text='n*1 array listing the type of each interval', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interval_series_interval_descriptions', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='interval_times',
            field=models.ForeignKey(blank=True, help_text='n*2 array, with associated array of row labels.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interval_series_interval_times', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interval_series_provenance', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='headtracking',
            name='experiment',
            field=models.ForeignKey(help_text='The Experiment to which this data belongs', on_delete=django.db.models.deletion.CASCADE, related_name='behavior_headtracking_related', to='actions.Experiment'),
        ),
        migrations.AddField(
            model_name='headtracking',
            name='movie',
            field=models.ForeignKey(blank=True, help_text='Link to raw data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_tracking_movie', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='headtracking',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_tracking_provenance', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='headtracking',
            name='x_y_theta',
            field=models.ForeignKey(blank=True, help_text='3*n timeseries giving x and y coordinates of head plus angle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_tracking_x_y_d', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='event_times',
            field=models.ForeignKey(blank=True, help_text='n*1 array of times in seconds', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_series_event_times', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='event_types_id',
            field=models.ForeignKey(blank=True, help_text='n*1 array listing the type of each event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_series_event_descriptions', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='experiment',
            field=models.ForeignKey(help_text='The Experiment to which this data belongs', on_delete=django.db.models.deletion.CASCADE, related_name='behavior_eventseries_related', to='actions.Experiment'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_series_provenance', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='type_descriptions_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Dataset'),
        ),
    ]
