# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('behavior', '0003_auto_20170426_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalseries',
            name='interval_descriptions',
        ),
        migrations.AddField(
            model_name='eventseries',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_eventseries_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The creation date.', null=True),
        ),
        migrations.AddField(
            model_name='headtracking',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_headtracking_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='headtracking',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The creation date.', null=True),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_intervalseries_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The creation date.', null=True),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='interval_types',
            field=models.ForeignKey(blank=True, help_text='n*1 array listing the type of each interval', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interval_series_interval_descriptions', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='intervalseries',
            name='type_descriptions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_optogeneticstimulus_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='optogeneticstimulus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The creation date.', null=True),
        ),
        migrations.AddField(
            model_name='pharmacology',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_pharmacology_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacology',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The creation date.', null=True),
        ),
        migrations.AddField(
            model_name='pupiltracking',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of the data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_pupiltracking_created_by_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pupiltracking',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The creation date.', null=True),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='event_times',
            field=models.ForeignKey(blank=True, help_text='n*1 array of times in seconds (universal timescale)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_series_event_times', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_eventseries_session_related', to='actions.Session'),
        ),
        migrations.AlterField(
            model_name='headtracking',
            name='movie',
            field=models.ForeignKey(blank=True, help_text='Link to raw data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_tracking_movie', to='data.TimeSeries'),
        ),
        migrations.AlterField(
            model_name='headtracking',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_headtracking_session_related', to='actions.Session'),
        ),
        migrations.AlterField(
            model_name='headtracking',
            name='x_y_theta',
            field=models.ForeignKey(blank=True, help_text='3*n timeseries giving x and y coordinates of head plus angle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_tracking_x_y_d', to='data.TimeSeries'),
        ),
        migrations.AlterField(
            model_name='intervalseries',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_intervalseries_session_related', to='actions.Session'),
        ),
        migrations.AlterField(
            model_name='optogeneticstimulus',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_optogeneticstimulus_session_related', to='actions.Session'),
        ),
        migrations.AlterField(
            model_name='pharmacology',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_pharmacology_session_related', to='actions.Session'),
        ),
        migrations.AlterField(
            model_name='pupiltracking',
            name='movie',
            field=models.ForeignKey(blank=True, help_text='Link to raw data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pupil_tracking_movie', to='data.TimeSeries'),
        ),
        migrations.AlterField(
            model_name='pupiltracking',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The Session to which this data belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_pupiltracking_session_related', to='actions.Session'),
        ),
        migrations.AlterField(
            model_name='pupiltracking',
            name='x_y_d',
            field=models.ForeignKey(blank=True, help_text='n*3 timeseries giving x and y coordinates of center plus diameter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pupil_tracking_x_y_d', to='data.TimeSeries'),
        ),
    ]
