# Generated by Django 2.0.6 on 2018-06-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0004_auto_20180111_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventseries',
            name='event_times',
            field=models.ForeignKey(blank=True, help_text='n*1 array of times in seconds (universal timescale)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_series_event_times', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='event_types_id',
            field=models.ForeignKey(blank=True, help_text='n*1 array listing the type of each event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_series_event_descriptions', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_series_provenance', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='type_descriptions_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='headtracking',
            name='movie',
            field=models.ForeignKey(blank=True, help_text='Link to raw data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_tracking_movie', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='headtracking',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_tracking_provenance', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='headtracking',
            name='x_y_theta',
            field=models.ForeignKey(blank=True, help_text='3*n timeseries giving x and y coordinates of head plus angle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_tracking_x_y_d', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='intervalseries',
            name='interval_times',
            field=models.ForeignKey(blank=True, help_text='n*2 array, with associated array of row labels.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interval_series_interval_times', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='intervalseries',
            name='interval_types',
            field=models.ForeignKey(blank=True, help_text='n*1 array listing the type of each interval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interval_series_interval_descriptions', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='intervalseries',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interval_series_provenance', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='intervalseries',
            name='type_descriptions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='optogeneticstimulus',
            name='apparatus',
            field=models.ForeignKey(blank=True, help_text='e.g. Laser that was used for stimulation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Appliance'),
        ),
        migrations.AlterField(
            model_name='optogeneticstimulus',
            name='brain_location',
            field=models.ForeignKey(blank=True, help_text='of fiber tip, craniotomy, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.BrainLocation'),
        ),
        migrations.AlterField(
            model_name='optogeneticstimulus',
            name='power',
            field=models.ForeignKey(blank=True, help_text='link to an n*1 array giving each pulse power', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optogenetic_stimulus_power', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='optogeneticstimulus',
            name='stimulus_positions',
            field=models.ForeignKey(blank=True, help_text='link to an n*3 array of stimulus positions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optogenetic_stimulus_positions', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='optogeneticstimulus',
            name='stimulus_times',
            field=models.ForeignKey(blank=True, help_text='link to an n*2 array of start and stop of each pulse (sec)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optogenetic_stimulus_times', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='optogeneticstimulus',
            name='waveform',
            field=models.ForeignKey(blank=True, help_text='link to a file giving the waveform of each stimulus.?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optogenetic_stimulus_waveform', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='pupiltracking',
            name='movie',
            field=models.ForeignKey(blank=True, help_text='Link to raw data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pupil_tracking_movie', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='pupiltracking',
            name='provenance_directory',
            field=models.ForeignKey(blank=True, help_text='link to directory containing intermediate results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pupil_tracking_provenance', to='data.Dataset'),
        ),
        migrations.AlterField(
            model_name='pupiltracking',
            name='x_y_d',
            field=models.ForeignKey(blank=True, help_text='n*3 timeseries giving x and y coordinates of center plus diameter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pupil_tracking_x_y_d', to='data.Dataset'),
        ),
    ]
