# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0002_auto_20160621_1230'),
        ('equipment', '0001_initial'),
        ('electrophysiology', '0001_initial'),
        ('data', '0001_initial'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intracellularrecording',
            name='pipette_puller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.PipettePuller'),
        ),
        migrations.AddField(
            model_name='intracellularrecording',
            name='recorded_current',
            field=models.ForeignKey(blank=True, help_text='nA. TODO: time series? flat file? sample rate?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intracellular_recording_recorded_current', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='intracellularrecording',
            name='recorded_voltage',
            field=models.ForeignKey(blank=True, help_text='mV', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intracellular_recording_recorded_voltage', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='intracellularrecording',
            name='tip_location',
            field=models.ForeignKey(blank=True, help_text='Estimated location of probe tip', null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.BrainLocation'),
        ),
        migrations.AddField(
            model_name='intracellularrecording',
            name='voltage_command',
            field=models.ForeignKey(blank=True, help_text='mV', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intracellular_recording_voltage_command', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='extracellularrecording',
            name='amplifier',
            field=models.ForeignKey(blank=True, help_text='The amplifier used in this recording.', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.Amplifier'),
        ),
        migrations.AddField(
            model_name='extracellularrecording',
            name='daq_description',
            field=models.ForeignKey(blank=True, help_text='The DAQ used.', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.DAQ'),
        ),
        migrations.AddField(
            model_name='extracellularrecording',
            name='experiment',
            field=models.ForeignKey(help_text='The Experiment to which this data belongs', on_delete=django.db.models.deletion.CASCADE, related_name='electrophysiology_extracellularrecording_related', to='actions.Experiment'),
        ),
        migrations.AddField(
            model_name='extracellularrecording',
            name='extracellular_probe',
            field=models.ForeignKey(blank=True, help_text='Which probe model was used.', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.ExtracellularProbe'),
        ),
        migrations.AddField(
            model_name='extracellularrecording',
            name='highpass_data',
            field=models.ForeignKey(blank=True, help_text='Extracellular high-passed data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracellular_recording_hpf', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='extracellularrecording',
            name='impedances',
            field=models.ForeignKey(blank=True, help_text='binary array for measured impedance of each channel (ohms).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracellular_impedances', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='extracellularrecording',
            name='lowpass_data',
            field=models.ForeignKey(blank=True, help_text='Extracellular low-passed data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracellular_recording_lpf', to='data.Dataset'),
        ),
        migrations.AddField(
            model_name='extracellularrecording',
            name='probe_location',
            field=models.ForeignKey(blank=True, help_text='from probe tip', null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.CoordinateTransformation'),
        ),
        migrations.AddField(
            model_name='extracellularrecording',
            name='raw_data',
            field=models.ForeignKey(blank=True, help_text='Raw electrophysiology recording data in flat binary format', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracellular_recording_raw', to='data.Dataset'),
        ),
    ]
