# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrophysiology', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intracellularrecording',
            old_name='Bridge_balance',
            new_name='bridge_balance',
        ),
        migrations.RenameField(
            model_name='intracellularrecording',
            old_name='Pipette_cap_comp',
            new_name='pipette_cap_comp',
        ),
    ]
