# docker build -t internationalbrainlab/alyx:django -f ./scripts/deployment_examples/docker-apache/Dockerfile.alyx.django .
# docker run -it -p 80:80 -p 443:443 --rm internationalbrainlab/alyx:django
# syntax=docker/dockerfile:1

FROM internationalbrainlab/alyx:base

ADD ./scripts/deployment_examples/docker-apache/settings.py /var/www/alyx/alyx/alyx/settings.py
ADD ./scripts/deployment_examples/docker-apache/settings_secret.py /var/www/alyx/alyx/alyx/settings_secret.py
ADD ./scripts/deployment_examples/docker-apache/settings_lab.py /var/www/alyx/alyx/alyx/settings_lab.py
ADD ./scripts/deployment_examples/docker-apache/site-config.conf /etc/apache2/sites-available/000-default.conf
ADD ./scripts/deployment_examples/docker-apache/ip_whitelist.conf /etc/apache2/sites-available/ip_whitelist.conf
ADD ./scripts/deployment_examples/docker-apache/fullchain.pem /etc/apache2/ssl/fullchain.pem
ADD ./scripts/deployment_examples/docker-apache/privkey.pem /etc/apache2/ssl/privkey.pem

EXPOSE 80 443
RUN echo "ServerName alyx-dev.internationalbrainlab.org" >> /etc/apache2/apache2.conf
RUN a2enmod ssl

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

RUN mkdir -p /backups/tables
WORKDIR /var/www/alyx/alyx
