# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 13:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('subjects', '0001_initial'), ('subjects', '0002_subject_responsible_user'), ('subjects', '0003_auto_20151119_2032'), ('subjects', '0004_auto_20151119_2051'), ('subjects', '0005_auto_20151125_1531'), ('subjects', '0006_auto_20160101_1124'), ('subjects', '0007_action'), ('subjects', '0008_auto_20160108_2108'), ('subjects', '0009_weighing'), ('subjects', '0010_action_tags'), ('subjects', '0011_remove_action_tags'), ('subjects', '0012_action_tags'), ('subjects', '0013_auto_20160111_0013'), ('subjects', '0014_auto_20160111_0030'), ('subjects', '0015_auto_20160111_0101'), ('subjects', '0016_auto_20160111_1624'), ('subjects', '0017_auto_20160112_0039'), ('subjects', '0018_auto_20160112_1012'), ('subjects', '0019_auto_20160112_1023'), ('subjects', '0020_auto_20160114_1417'), ('subjects', '0021_auto_20160114_1417'), ('subjects', '0022_auto_20160114_1420'), ('subjects', '0023_auto_20160114_1456'), ('subjects', '0024_auto_20160114_1502'), ('subjects', '0025_virus_batch_virus_injection'), ('subjects', '0026_litter_descriptive_name'), ('subjects', '0027_auto_20160209_1350')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Species')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('strain', models.CharField(max_length=255)),
                ('genotype', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('birth_date_time', models.DateTimeField(blank=True, null=True)),
                ('death_date_time', models.DateTimeField(blank=True, null=True)),
                ('responsible_user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subjects_responsible', to=settings.AUTH_USER_MODEL)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('binomial', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weighing',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subjects.Action')),
                ('weight', models.FloatField()),
            ],
            bases=('subjects.action',),
        ),
        migrations.AddField(
            model_name='action',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=30),
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subjects.Action')),
                ('procedure', models.CharField(max_length=255)),
                ('brain_location', models.CharField(max_length=255)),
            ],
            bases=('subjects.action',),
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'species'},
        ),
        migrations.AlterModelOptions(
            name='surgery',
            options={'verbose_name_plural': 'surgeries'},
        ),
        migrations.AddField(
            model_name='action',
            name='JSON',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.AlterField(
            model_name='action',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subjects.Action')),
            ],
            bases=('subjects.action',),
        ),
        migrations.AlterField(
            model_name='action',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='genotype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='strain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='action',
            name='JSON',
        ),
        migrations.AlterField(
            model_name='action',
            name='start_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='JSON',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litter_father', to='subjects.Subject')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litter_mother', to='subjects.Subject')),
                ('descriptive_name', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='action',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Litter'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='brain_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='procedure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Virus_Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('virus_type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('virus_source', models.CharField(blank=True, max_length=255, null=True)),
                ('date_time_made', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('nominal_titer', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Virus_Injection',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subjects.Action')),
                ('injection_volume', models.FloatField(blank=True, null=True)),
                ('rate_of_injection', models.FloatField(blank=True, null=True)),
                ('injection_type', models.CharField(blank=True, choices=[('I', 'Iontophoresis'), ('P', 'Pressure')], default='I', max_length=1, null=True)),
                ('virus_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Virus_Batch')),
            ],
            bases=('subjects.action',),
        ),
        migrations.AlterField(
            model_name='subject',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
