# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='action',
            name='users',
        ),
        migrations.RemoveField(
            model_name='note',
            name='action_ptr',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='action_ptr',
        ),
        migrations.RemoveField(
            model_name='virus_injection',
            name='action_ptr',
        ),
        migrations.RemoveField(
            model_name='virus_injection',
            name='virus_batch',
        ),
        migrations.RemoveField(
            model_name='weighing',
            name='action_ptr',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Surgery',
        ),
        migrations.DeleteModel(
            name='Virus_Batch',
        ),
        migrations.DeleteModel(
            name='Virus_Injection',
        ),
        migrations.DeleteModel(
            name='Weighing',
        ),
    ]
