# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20160513_1345'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allele',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standard_name', models.CharField(help_text='MGNC-standard genotype name e.g. Pvalb<tm1(cre)Arbr>, http://www.informatics.jax.org/mgihome/nomen/', max_length=1023)),
                ('informal_name', models.CharField(help_text='informal name in lab, e.g. Pvalb-Cre', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('I', 'IVC'), ('R', 'Regular')], default='I', help_text='Is this an IVC or regular cage?', max_length=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.LabLocation')),
            ],
        ),
        migrations.AlterField(
            model_name='species',
            name='binomial',
            field=models.CharField(help_text='Binomial name, e.g. "mus musculus"', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='display_name',
            field=models.CharField(help_text='common name, e.g. "mouse"', max_length=255),
        ),
        migrations.AlterField(
            model_name='strain',
            name='descriptive_name',
            field=models.CharField(help_text='Standard descriptive name E.g. "C57BL/6J", http://www.informatics.jax.org/mgihome/nomen/', max_length=255),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='genotype',
        ),
        migrations.AlterField(
            model_name='subject',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Species'),
        ),
        migrations.DeleteModel(
            name='Genotype',
        ),
        migrations.AddField(
            model_name='subject',
            name='cage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Cage'),
        ),
        migrations.AddField(
            model_name='subject',
            name='genotype',
            field=models.ManyToManyField(to='subjects.Allele'),
        ),
    ]
