# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zygosity',
            name='zygosity',
            field=models.IntegerField(choices=[(0, 'Absent'), (1, 'Heterozygous'), (2, 'Homozygous')]),
        ),
    ]
