# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20160422_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='descriptive_name',
            new_name='name',
        ),
    ]
