# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20160422_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genotype',
            name='descriptive_name',
            field=models.CharField(help_text='Standard descriptive name, http://www.informatics.jax.org/mgihome/nomen/', max_length=255),
        ),
        migrations.AlterField(
            model_name='species',
            name='binomial',
            field=models.CharField(help_text='Binomial name, i.e. "mus musculus"', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='strain',
            name='descriptive_name',
            field=models.CharField(help_text='Standard descriptive name, http://www.informatics.jax.org/mgihome/nomen/', max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='nickname',
            field=models.CharField(blank=True, help_text='Easy-to-remember, unique name (e.g. “Hercules”).', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='responsible_user',
            field=models.ForeignKey(blank=True, help_text='Who has primary or legal responsibility for the subject.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects_responsible', to=settings.AUTH_USER_MODEL),
        ),
    ]
