# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_action_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='tags',
        ),
    ]
