# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 17:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_remove_action_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=30),
        ),
    ]
