# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_action_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subjects.Action')),
                ('procedure', models.CharField(max_length=255)),
                ('brain_location', models.CharField(max_length=255)),
            ],
            bases=('subjects.action',),
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'species'},
        ),
    ]
