# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 00:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0013_auto_20160111_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surgery',
            options={'verbose_name_plural': 'surgeries'},
        ),
        migrations.AddField(
            model_name='action',
            name='JSON',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
