# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 01:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_auto_20160111_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='JSON',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
