# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 16:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0015_auto_20160111_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.AddField(
            model_name='subject',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_father', to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_mother', to='subjects.Subject'),
        ),
        migrations.AlterField(
            model_name='action',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='weight',
            field=models.FloatField(),
        ),
    ]
