# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 10:23
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0018_auto_20160112_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='JSON',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
