# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0020_auto_20160114_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
