# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0021_auto_20160114_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='litter',
        ),
        migrations.AddField(
            model_name='subject',
            name='litter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Litter'),
        ),
    ]
