# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0023_auto_20160114_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='brain_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='procedure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
