# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0025_virus_batch_virus_injection'),
    ]

    operations = [
        migrations.AddField(
            model_name='litter',
            name='descriptive_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
