# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0026_litter_descriptive_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virus_injection',
            old_name='virus_batch_id',
            new_name='virus_batch',
        ),
        migrations.AlterField(
            model_name='subject',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Litter'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
