ServerAdmin ${APACHE_SERVER_ADMIN}
DocumentRoot /var/www/alyx

<Directory /var/www/alyx/alyx/alyx>
    <Files wsgi.py>
        Require all granted
    </Files>
</Directory>

Alias /static/ /var/www/alyx/alyx/static/
Alias /uploaded/ /var/www/alyx/alyx/uploaded/
Alias /.well-known/ /var/www/alyx/.well-known/

<Directory /var/www/alyx/.well-known>
    Require all granted
</Directory>

<Directory /var/www/alyx/alyx/static>
    Require all granted
</Directory>

<Directory /var/www/alyx/alyx/uploaded>
    Require all granted
</Directory>

ErrorLog "|/usr/bin/rotatelogs -n 5 ${APACHE_LOG_DIR}/error_alyx.log 128M"
CustomLog "|/usr/bin/rotatelogs -n 5 ${APACHE_LOG_DIR}/access_alyx.log 128M" combined

WSGIApplicationGroup %{GLOBAL}
WSGIDaemonProcess alyx python-path=/var/www/alyx/alyx python-home=/var/www/alyx/.venv socket-user=#33 listen-backlog=50 request-timeout=300 maximum-requests=1000
WSGIProcessGroup alyx
WSGIScriptAlias / /var/www/alyx/alyx/alyx/wsgi.py
WSGIPassAuthorization On