version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: ./launch.sh
    volumes:
      - .:/code
    ports:
      - "8000:80"
    depends_on:
      - db

