# Generated by Django 2.1 on 2018-11-19 09:30

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='reference_weight_pct',
            field=models.FloatField(default=0.0, help_text='The minimum mouse weight is a linear combination of the reference weight and the zscore weight.'),
        ),
        migrations.AddField(
            model_name='lab',
            name='zscore_weight_pct',
            field=models.FloatField(default=0.0, help_text='The minimum mouse weight is a linear combination of the reference weight and the zscore weight.'),
        ),
        migrations.AlterField(
            model_name='labmembership',
            name='start_date',
            field=models.DateField(blank=True, null=True, default=timezone.now),
        ),
    ]
