# Generated by Django 2.1.2 on 2018-11-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='reference_weight_pct',
            field=models.FloatField(default=0.0, help_text='The minimum mouse weight is a linear combination of the reference weight and the zscore weight.'),
        ),
        migrations.AddField(
            model_name='lab',
            name='zscore_weight_pct',
            field=models.FloatField(default=0.0, help_text='The minimum mouse weight is a linear combination of the reference weight and the zscore weight.'),
        ),
    ]
