# Generated by Django 2.1.3 on 2018-12-13 12:12

from django.db import migrations, models
import django.db.models.deletion


def set_defaults(apps, schema_editor):
    Lab = apps.get_model('misc', 'Lab')
    lab = Lab.objects.first()
    LabLocation = apps.get_model('misc', 'LabLocation')
    LabLocation.objects.update(lab=lab)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_auto_20181119_0930'),
    ]

    operations = [
        migrations.RunPython(set_defaults, reverse_func),

        migrations.AlterField(
            model_name='lablocation',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.Lab'),
        ),
    ]
