# Generated by Django 2.1.2 on 2018-11-16 19:49

from django.db import migrations


def forward(apps, schema_editor):
    Lab = apps.get_model('misc', 'Lab')
    if Lab.objects.filter(name='cortexlab'):
        return
    lab = Lab.objects.create(
        pk='4027da48-7be3-43ec-a222-f75dffe36872',
        name='cortexlab',
        institution='University College London',
        address='Cruciform Building, Gower Street, London, WC1E 6BT, United Kingdom',
        timezone='Europe/London',
        reference_weight_pct=0.,
        zscore_weight_pct=.8,
    )
    Subject = apps.get_model('subjects', 'Subject')
    Subject.objects.all().update(lab=lab)


def backward(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_auto_20181116_1530'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
