# Generated by Django 2.1.4 on 2019-01-23 18:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_auto_20181119_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lablocation',
            name='lab',
            field=models.ForeignKey(default=uuid.UUID('4027da48-7be3-43ec-a222-f75dffe36872'), on_delete=django.db.models.deletion.CASCADE, to='misc.Lab'),
        ),
    ]
