# Generated by Django 2.1 on 2018-11-17 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_auto_20181116_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmembership',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
