# Generated by Django 3.0 on 2019-12-24 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_lab_repositories'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmember',
            name='allowed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
