# Generated by Django 3.0 on 2020-01-20 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_labmember_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmember',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
