# Generated by Django 5.0 on 2024-03-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0009_auto_20211122_1535"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="Europe/London",
                help_text="Timezone of the server (see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)",
                max_length=64,
            ),
        ),
    ]
