# Generated by Django 3.2.4 on 2022-03-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0009_auto_20211122_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmember',
            name='is_public_user',
            field=models.BooleanField(default=False),
        ),
    ]
