# Generated by Django 5.2.8 on 2025-11-07 17:44

import misc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0011_alter_lab_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='timezone',
            field=models.CharField(blank=True, default=misc.models.default_timezone, help_text='Timezone of the server (see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)', max_length=64),
        ),
    ]
