# Generated by Django 5.2.16 on 2026-07-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0012_alter_lab_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='reference_weight_pct',
            field=models.FloatField(default=0.0, help_text="Fraction (0–1) of the mouse's own reference weight (weight at water-restriction start) used as the minimum acceptable weight threshold. E.g. 0.85 requires the mouse to stay above 85 % of its reference weight."),
        ),
        migrations.AlterField(
            model_name='lab',
            name='zscore_weight_pct',
            field=models.FloatField(default=0.0, help_text="Fraction (0–1) of the age/sex population-normalised (z-score) weight used as the minimum acceptable weight threshold. The z-score weight projects the mouse's weight z-score at water-restriction start onto the population growth curve at the current age. E.g. 0.85 requires the mouse to stay above 85 % of its expected age/sex weight. When both zscore_weight_pct and reference_weight_pct are non-zero, the expected weight is their weighted average."),
        ),
    ]
