# Generated by Django 5.2.17 on 2026-09-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0013_alter_lab_reference_weight_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmember',
            name='json',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
