# Generated by Django 5.2.16 on 2026-08-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0013_alter_lab_reference_weight_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmember',
            name='is_redacted',
            field=models.BooleanField(default=False, help_text="This user's identifying details have been stripped. The record is kept so that the subjects, sessions and datasets attributed to it remain queryable, but it holds no usable credentials and should not be treated as a real account."),
        ),
    ]
