# Generated by Django 2.2.6 on 2020-02-27 17:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0006_dataset_hash_version'),
        ('actions', '0009_ephyssession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('name', models.CharField(max_length=128)),
                ('priority', models.SmallIntegerField(blank=True, null=True)),
                ('gpu', models.SmallIntegerField(blank=True, null=True)),
                ('cpu', models.SmallIntegerField(blank=True, null=True)),
                ('depends_on', models.ManyToManyField(related_name='_task_depends_on_+', to='jobs.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Long name', max_length=255)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Structured data, formatted in a user-defined way', null=True)),
                ('status', models.IntegerField(choices=[(10, 'Pending'), (20, 'Running'), (30, 'Errored'), (40, 'Complete')], default=10)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.CharField(blank=True, help_text='version of the algorithm generating the file', max_length=64, null=True)),
                ('data_repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='data.DataRepository')),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='data.Dataset')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='actions.Session')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
