# Generated by Django 4.0.6 on 2022-09-13 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_datasettype_filename_pattern_and_more'),
        ('jobs', '0007_remove_task_unique_task_name_per_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data_repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='data.datarepository'),
        ),
    ]
